main/urls.py
from django.urls import path
from . import views
# from .api import TempatViewSet
# from rest_framework import routers

app_name = 'main'

# router = routers.DefaultRouter()
# router.register('api/main', TempatViewSet, 'viewset')

urlpatterns = [
    path('', views.landing, name='landing'),
    path('add_message/', views.form, name='add_message'),
    path('message_list/', views.message_list, name='message_list'),
    path('price_today/', views.price_today, name='price_today'),
    path('randomizer/', views.place_randomizer, name='randomizer'),
    path('nggabut/', views.nggabut, name='nggabut'),
    path('api/viewall/', views.postList),
    path('api/create/', views.createPost),
    path('post/', views.post, name='post')
]

sarekatjum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

class Pesan(models.Model):
    sender_name   = models.CharField(max_length = 50)
    receiver_name = models.CharField(max_length = 50)
    message       = models.TextField()
    date          = models.DateField(auto_now_add=True)

class Tempat(models.Model):
    nama_tempat	= models.CharField(max_length = 255)
    tipe_tempat	= models.CharField(max_length = 255)
    lokasi = models.CharField(max_length = 255)
    keterangan_tempat = models.TextField()
    jam_buka = models.CharField(max_length = 255)
    price_range_spesifik = models.CharField(max_length = 255, default=None, blank=True, null=True)	
    mampu_beli = models.CharField(max_length = 255)
    link_maps = models.CharField(max_length = 255)
    parkir = models.CharField(max_length = 255, default=None, blank=True, null=True)
    plus = models.TextField(default=None, blank=True, null=True)
    minus = models.TextField(default=None, blank=True, null=True)
    class Meta:
        db_table = "tempat"

main/forms.py
from django import forms
from django.forms import fields
from .models import Pesan, Tempat

class inputForm(forms.ModelForm):
    class Meta:
        model  = Pesan
        fields = '__all__'
    
class jalanForm(forms.Form):
    location = forms.ChoiceField(choices=[('bintaro','Bintaro'),
        ('bsd','BSD')], widget=forms.RadioSelect(attrs={'class': "form-check-inline"}), label='Mau Jalan Kemana Bestie?')
    activity = forms.ChoiceField(choices=[('makan','Makan'),
        ('nongkrong','Nongkrong')], widget=forms.RadioSelect(attrs={'class': "form-check-inline"}), label='Mau Ngapain Nih Bestie?')
    price = forms.ChoiceField(choices=[('murah','Murah'),
    ('sedeng','Sedeng'), ('mehong','Mehong')], widget=forms.RadioSelect(attrs={'class': "form-check-inline"}), label='Mau Harga Berapa Bestie?')
    class Meta:
        model  = Tempat

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from .models import Pesan, Tempat
import requests
import random
from django.forms.models import model_to_dict
from datetime import datetime
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import PostSerializer
from main import serializers
from .forms import inputForm, jalanForm


def landing(request):
    return render(request, 'main/landing.html')

@api_view(['GET'])
def postList(request):
    pesan = Pesan.objects.all().order_by('-id')
    serializer = PostSerializer(pesan, many=True)
    return Response(serializer.data)

    # if (form.is_valid() and request.method == "POST"):
    #     form.save()
    #     return  HttpResponseRedirect('/message_list')
@api_view(['POST'])
def createPost(request):
    serializer = PostSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()

        return Response(serializer.data)

def post(request):
    form = inputForm(initial={'sender_name':'anonymous', 'receiver_name':'everyone'})
    return render(request, 'main/anonymous_post.html', {'form' : form})


###! message feature ####
def add_message(request):
    form = inputForm()
    form.fields['sender_name'].initial = 'anonymous'
    form.fields['receiver_name'].initial = 'someone better than me'
    return render(request, 'main/add.html', {'form' : form})

def message_list(request):
    pesan_isi = Pesan.objects.all()
    context = {
        'pesan' : pesan_isi
    }
    return render(request, 'main/list.html', context)

def form(request):
    form = inputForm(request.POST)
    context = {
        'form' : form
    }
    if(form.is_valid() and request.method == "POST"):
        form.save()
        return  HttpResponseRedirect('/message_list')

    return render(request, 'main/add.html', context)

def delete(request, id):
    try:
        Pesan.objects.get(id=id).delete()
        return HttpResponseRedirect('/message_list')
    except Exception:
        return HttpResponseRedirect('/message_list')

###! Bitcoin Price Feature ###
def price_today(request):
    response = requests.get('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd&include_24hr_change=true').json()
    
    data = {}
    data["price"]  = response["bitcoin"]["usd"]
    data["change"] = round(response["bitcoin"]["usd_24h_change"], 2)
    if data["change"] > 0:
        data["up"] = "true"

    time = datetime.now()
    time_formatted = time.strftime("%H") +":" + time.strftime("%M") + " " + time.strftime("%x")

    context = {'data':data, 'time':time_formatted}
    return render(request, 'main/price_today.html', context)

###! Place Search & Randomizer ###
def place_randomizer(request):

    form = jalanForm(request.GET)
    tempat = Tempat.objects.all()
    tempat_list = []
    for i in tempat:
        tempat_dict = model_to_dict(i)
        tempat_list.append(tempat_dict)

    context = {'form':jalanForm(), 'tempat_list':tempat_list}

    if request.GET.get('submit') == 'clicked':
        location = request.GET.get('location').upper()
        activity = request.GET.get('activity').upper()
        price = request.GET.get('price').upper()
        tempat = Tempat.objects.filter(lokasi=location).filter(tipe_tempat=activity).filter(mampu_beli=price)
        tempat_list = []
        for i in tempat:
            tempat_dict = model_to_dict(i)
            tempat_list.append(tempat_dict)

        try:
            output = random.choice(tempat_list)
            context = {'form':form, 'output':output, 'tempat_list':tempat_list, 'location': location}

            return render(request, 'main/jalan_kemana.html', context)
        
        except:
            output = 'ngg ada bos'
            context = {'form':form, 'output':output}
            return render(request, 'main/jalan_kemana.html', context)
    
    else:
        return render(request, 'main/jalan_kemana.html', context)


def nggabut(request):
    return render(request, 'main/nggabut.html')

main/templates/main/anonymous_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/twit.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Work+Sans:wght@700&display=swap"
      rel="stylesheet"
    />
    <title>Welcome to SJWebsite</title>
  </head>

  <body
    style="
      background-color: #ff0000;
      background-image: radial-gradient(
          at 40% 20%,
          hsla(28, 100%, 74%, 1) 0,
          transparent 50%
        ),
        radial-gradient(at 80% 0%, hsla(189, 100%, 56%, 1) 0, transparent 50%),
        radial-gradient(at 0% 50%, hsla(355, 85%, 93%, 1) 0, transparent 50%),
        radial-gradient(at 80% 50%, hsla(340, 100%, 76%, 1) 0, transparent 50%),
        radial-gradient(at 0% 100%, hsla(22, 100%, 77%, 1) 0, transparent 50%),
        radial-gradient(at 80% 100%, hsla(242, 100%, 70%, 1) 0, transparent 50%),
        radial-gradient(at 0% 0%, hsla(343, 100%, 76%, 1) 0, transparent 50%);
    "
  >
    <!-- Navbar section -->
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-sm">
        <a class="navbar-brand" href="{% url 'main:landing'%}">SJW.</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href="{% url 'main:landing'%}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:price_today'%}"
                >Bitcoin Price</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:randomizer'%}"
                >Where to?</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'main:post'%}">Post</a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="https://gabutd.netlify.app">Gabut</a>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>
    <!-- Content section -->
    <div class="container p-4">
      <h1 class="text-center my-5" id="test">Curhat Zone</h1>
      <div class="container" id="form-wrapper">
        <form style="font-family: 'Inter', sans-serif" id="form">
          <div class="row g-3">
            <div class="col-md">
              <div class="form-floating">
                <input
                  type="text"
                  class="form-control"
                  id="from"
                  placeholder="name@example.com"
                  value="anonymous"
                  style="background-color: transparent; border: 1px solid black"
                />
                <label for="from">From</label>
              </div>
            </div>
            <div class="col-md">
              <div class="form-floating mb-3">
                <input
                  type="text"
                  class="form-control"
                  id="to"
                  placeholder="name@example.com"
                  value="everyone"
                  style="background-color: transparent; border: 1px solid black"
                />
                <label for="to">To</label>
              </div>
            </div>
          </div>
          <div class="form-floating">
            <textarea
              class="form-control"
              placeholder="tulis donk.."
              id="message"
              style="background-color: transparent; border: 1px solid black"
            ></textarea>
            <label for="message">Message</label>
          </div>

          <div class="d-flex justify-content-end">
            <button
              type="submit"
              value="clicked"
              name="submit"
              id="submit"
              class="btn btn-dark rounded-5 my-3 px-4 py-2"
            >
              Tweet
            </button>
          </div>
        </form>
      </div>

      <div class="container mt-5" style="font-family: 'Inter', sans-serif">
        <div class="text-center">
          <div class="spinner-grow" role="status" id="spinner">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
        <div
          class="d-flex flex-column align-items-center"
          id="post-wrapper"
        ></div>
      </div>
    </div>

    <!-- Footer section -->
    <div class="container">
      <footer class="py-3 my-4">
        <div class="border-bottom pb-3 mb-3"></div>
        <p class="text-center text-muted">
          &copy; 2022 Supportive Friendship, Inc
        </p>
        <div class="d-flex justify-content-center">
          <a href="https://gitlab.com/farizwhyzn/sarekatjum" target="_blank">
            <i class="fab fa-gitlab fa-2x" style="color: #e24329"></i>
          </a>
        </div>
      </footer>
    </div>

    <!-- Javascript -->
    <script
      src="https://kit.fontawesome.com/024646a2ae.js"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script>
      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          const cookies = document.cookie.split(";");
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      }
      const csrftoken = getCookie("csrftoken");

      buildList();

      function buildList() {
        const wrapper = document.getElementById("post-wrapper");
        const url = "http://sarekatjum.herokuapp.com/api/viewall/";
        wrapper.innerHTML = "";

        fetch(url)
          .then((resp) => resp.json())
          .then(function (data) {
            console.log("Data:", data);

            let list = data;
            for (let i in list) {
              let item = `
                    <div class="my-3 p-5 align-self-stretch" style="
                      background: rgba( 255, 255, 255, 0.25 );
                      box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
                      backdrop-filter: blur( 4px );
                      -webkit-backdrop-filter: blur( 4px );
                      border-radius: 10px;
                      border: 1px solid rgba( 255, 255, 255, 0.18 );">
                        <div class="d-flex flex-row justify-content-between" id="pp_name_icon">
                            <div class="d-flex" id="pp_and_name">
                                <i class="fas fa-user-circle fa-3x"></i>
                                <div class="align-self-center ms-3 fw-bold">${list[i].sender_name} · <span class="fst-italic fw-light">to ${list[i].receiver_name}</span> · <span class="fw-light text-muted">${list[i].date}</span></div>
                            </div>
                            <i class="fab fa-twitter fa-2x d-none d-sm-block"></i>
                        </div>
                        <h3 class="mt-4 lh-base">${list[i].message}</h3>
                    </div>
                `;
              wrapper.innerHTML += item;
            }
            document.getElementById("spinner").style.display = "none";
          });
      }

      const form = document.getElementById("form-wrapper");
      form.addEventListener("submit", function (e) {
        e.preventDefault();
        console.log("submitted");
        const url = "http://sarekatjum.herokuapp.com/api/create/";
        let from = document.getElementById("from").value;
        let to = document.getElementById("to").value;
        let message = document.getElementById("message").value;

        fetch(url, {
          method: "POST",
          headers: {
            "Content-type": "application/json",
            "X-CSRFToken": csrftoken,
          },
          body: JSON.stringify({
            sender_name: from,
            receiver_name: to,
            message: message,
          }),
        }).then(function (response) {
          buildList();
          document.getElementById("form").reset();
        });
      });
    </script>
  </body>
</html>

main/templates/main/jalan_kemana.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Work+Sans:wght@700&display=swap"
      rel="stylesheet"
    />
    <title>Welcome to SJWebsite</title>
  </head>

  <body style="background-color: black; color: white">
    <!-- Navbar section -->
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container-sm">
        <a class="navbar-brand" href="{% url 'main:landing'%}">SJW.</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href="{% url 'main:landing'%}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:price_today'%}"
                >Bitcoin Price</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'main:randomizer'%}"
                >Where to?</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:post'%}">Post</a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="https://gabutd.netlify.app">Gabut</a>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-5 p-4">
      <h1 class="fw-bold">Random Bestie Nongki Place Generator</h1>

      <form
        action="/randomizer/"
        method="GET"
        style="font-family: 'Inter', sans-serif"
      >
        <div class="d-flex flex-column justify-content-center">
          <label class="form-label text-center mt-3"
            >Mau Jalan Kemana Bestie?</label
          >
          <div class="mx-auto">
            <div class="form-check form-check-inline">
              <input
                class="form-check-input"
                type="radio"
                name="location"
                id="location1"
                value="bintaro"
                required
              />
              <label class="form-check-label" for="location1">Bintaro</label>
            </div>
            <div class="form-check form-check-inline">
              <input
                class="form-check-input"
                type="radio"
                name="location"
                id="location2"
                value="bsd"
              />
              <label class="form-check-label" for="location2">BSD</label>
            </div>
          </div>

          <label class="form-label text-center mt-4"
            >Mau Ngapain Nih Bestie?</label
          >
          <div class="mx-auto">
            <div class="form-check form-check-inline">
              <input
                class="form-check-input"
                type="radio"
                name="activity"
                id="activity1"
                value="makan"
                required
              />
              <label class="form-check-label" for="activity1">Makan</label>
            </div>
            <div class="form-check form-check-inline">
              <input
                class="form-check-input"
                type="radio"
                name="activity"
                id="activity2"
                value="nongkrong"
              />
              <label class="form-check-label" for="activity2">Nongkrong</label>
            </div>
          </div>

          <label class="form-label text-center mt-4"
            >Mau Harga Berapa Bestie?</label
          >
          <div class="mx-auto">
            <div class="form-check form-check-inline">
              <input
                class="form-check-input"
                type="radio"
                name="price"
                id="price1"
                value="murah"
                required
              />
              <label class="form-check-label" for="price1">Murah</label>
            </div>
            <div class="form-check form-check-inline">
              <input
                class="form-check-input"
                type="radio"
                name="price"
                id="price2"
                value="sedeng"
              />
              <label class="form-check-label" for="price2">Sedeng</label>
            </div>
            <div class="form-check form-check-inline">
              <input
                class="form-check-input"
                type="radio"
                name="price"
                id="price3"
                value="mehong"
              />
              <label class="form-check-label" for="price3">Mehong</label>
            </div>
          </div>
          <button
            type="submit"
            value="clicked"
            name="submit"
            class="btn btn-dark m-5 mx-auto px-4 py-2"
          >
            Hayyu
          </button>
        </div>
      </form>

      {% if output.nama_tempat %}
      <div
        class="container border border-dark rounded-3 p-1 p-md-5"
        id="result"
      >
        <div class="d-flex flex-column flex-md-row">
          <div class="ratio ratio-1x1 mb-5" id="maps_embed">
            <iframe
              width="100%"
              height="100%"
              style="border: 0"
              loading="lazy"
              allowfullscreen
              src="https://www.google.com/maps/embed/v1/place?key=AIzaSyD_oGZ_g_glYlKf0cx0s-ozRt-cLiP38V0&q={{output.nama_tempat}}+{{location}}&maptype=satellite"
            >
            </iframe>
          </div>
          <div
            class="container"
            id="texts"
            style="font-family: 'Inter', sans-serif"
          >
            <div class="d-flex flex-column align-items-start mx-5">
              <div class="container align-self-center" id="name_and_desc">
                <h1 class="mb-3 text-start">{{output.nama_tempat}}</h1>
                <figure class="text-center">
                  <blockquote class="blockquote text-start">
                    <p class="lh-base">"{{output.keterangan_tempat}}"</p>
                  </blockquote>
                  <figcaption class="blockquote-footer">
                    <cite title="Manusia">Manusia</cite>
                  </figcaption>
                </figure>
              </div>
              <div class="container align-self-center" id="info">
                <div class="d-flex flex-row">
                  <i class="fas fa-clock fa-2x my-3 me-3"></i>
                  <div class="align-self-center">{{output.jam_buka}}</div>
                </div>
                <div class="d-flex flex-row">
                  <i class="fas fa-dollar-sign fa-2x my-3 me-3"></i>
                  <div class="align-self-center">
                    {{output.price_range_spesifik}}
                  </div>
                </div>
                <div class="d-flex flex-row">
                  <i class="fas fa-parking fa-2x my-3 me-3"></i>
                  <div class="align-self-center">{{output.parkir}}</div>
                </div>
                <div class="d-flex flex-row">
                  <i class="fas fa-thumbs-up fa-2x my-3 me-3"></i>
                  <div class="align-self-center">{{output.plus}}</div>
                </div>
                <div class="d-flex flex-row">
                  <i class="fas fa-thumbs-down fa-2x my-3 me-3"></i>
                  <div class="align-self-center">{{output.minus}}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% else %}
      <div id="result_alt">
        <h1 class="display-6" style="margin-bottom: 10rem">{{output}}</h1>
      </div>
      {% endif %}
    </div>

    <!-- Footer section -->
    <div class="container">
      <footer class="py-3 my-4">
        <div class="border-bottom pb-3 mb-3"></div>
        <p class="text-center text-muted">
          &copy; 2022 Supportive Friendship, Inc
        </p>
      </footer>
    </div>

    <script
      src="https://kit.fontawesome.com/024646a2ae.js"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script>
      document.querySelector("#result").scrollIntoView({ behavior: "smooth" });
      document
        .querySelector("#result_alt")
        .scrollIntoView({ behavior: "smooth" });
    </script>
  </body>
</html>